### ISSUE TITLE
Roadmap for v5

### ISSUE THREAD

**Issue by ibell** [CoolProp/CoolProp#69]
- [ ] Make all Catch tests pass
- [x] Remaining "normal" solvers with pressure given (PH, PS, PU)
- [x] Phase envelope inside/outside calculation (same for pure fluids)
- [x] HS solvers
- [ ] Add consistency plots for all fluids
- [ ] Add REFPROP 9.1 comparisons for saturation curves
- [x] Finish scilab wrapper
